### ISSUE TITLE
【PC】背景映像がグレーがかっているため文字の可読性が低い

### ISSUE THREAD

**Issue by nama-gatsuo** [croe/iamas2018-web#11]
ストリーミング画像がそこそこグレー（白くない）なので、文字の可読性が悪い。とく特にプトジェクト一覧など。
<img width="50%" alt="screenshot" src="https://user-images.githubusercontent.com/7838131/35565453-edf9cc88-0600-11e8-9828-bf11147cb3a6.png">
これを解消するために、main.layout__container--wrapperなどが持つ、backgroundの透過率を下げたい。

**Comment by croe** [comment]
トップページ以外はライト制御ボタンもないので、透過率下げでよいと思います
