### ISSUE TITLE
Related（関連コーナー）の情報の位置について

### ISSUE THREAD

**Issue by croe** [croe/iamas2018-web#7]
南原食堂は写真が来る予定なので、どこにどのようにのせるか
そもそものIndexの下部にセクションなのか、別ページを用意するか

**Comment by nama-gatsuo** [comment]
1) indexの下部にセクション用意
2) Eventページの下部or上部にOther event的なセクション設置
3) 別の階層を設ける

2), 3)はより分類が難しく、かつ、新規のレイアウトを実装する手間があるので、1)が良いと考えています。
@croe どう思います？

**Comment by croe** [comment]
@nama-gatsuo 南原食堂だけ写真があることになるので、例えばゲストとかを写真載せるレイアウトにできるなら①案でもよいかと。2は気付かれにくく、3はユーザのクリック等が必要になるので、きれいに見せたい作り手のエゴ的なところになりそう

**Comment by nama-gatsuo** [comment]
1) indexの下部にセクション用意
の方向で実装を進めますね。
